%define name gcc-plugin-dehydra
%define gccdir %(gcc -print-file-name=plugin)

Name:		%{name}
Version:	0.0.hg563
Release:	1
License:	GPLv2
Summary:	GCC Dehydra Plugin
Group:		Development/C++
URL:		http://hg.mozilla.org/rewriting-and-analysis/dehydra/
Source0:	%{name}-0.0.hg563.tar.bz2
Requires:	gcc
Suggests:	%{name}-doc
Suggests:	%{name}-treehydra
Requires:	gcc-plugin-devel
Requires:	gmp-devel
Requires:	ppl-devel
Requires:	ppl_c-devel
Requires:	mpfr-devel
Requires:	libmpc-devel
BuildRequires:	gcc-plugin-devel
BuildRequires:  gmp-devel
BuildRequires:  ppl-devel
BuildRequires:  ppl_c-devel
BuildRequires:  mpfr-devel
BuildRequires:  libmpc-devel
BuildRequires:	mozjs-devel

%description
Dehydra is a lightweight, scriptable, general purpose static analysis
tool capable of application-specific analyses of C++ code. In the
simplest sense, Dehydra can be thought of as a semantic grep tool. It
presents a wealth of semantic information that can be queried with
concise JavaScripts. It is also useful to find bugs in source code as it
allows for much more error checking than C++ is capable of by itself.
Dehydra is built as a GCC plugin, thus it is easy to use for projects
that already support GCC.

Dehydra is also useful for generating language bindings and is used to
bootstrap Treehydra, a heavy-duty static analysis GCC plugin.

%files
%{gccdir}/gcc_dehydra.so

%package	-n gcc-plugin-treehydra
Summary:	GCC Treehydra Plugin
Group:		Development/C++
URL:		https://developer.mozilla.org/en/Treehydra
Suggests:	%{name}-doc
Requires:	gcc
Requires:	gcc-plugin-devel
Requires:	gmp-devel
Requires:	ppl-devel
Requires:	ppl_c-devel
Requires:	mpfr-devel
Requires:	libmpc-devel

%description	-n gcc-plugin-treehydra 
Treehydra is a GCC plugin that provides a low level JavaScript binding
to GCC's GIMPLE AST representation. Treehydra is intended for precise
static analyses.

Most of Treehydra is generated by Dehydra. A Dehydra script walks the
GCC tree node structure using the GTY attributes present in GCC.
Treehydra is included in Dehydra source, and is built when a
plugin-enabled CXX is detected.

%files	-n gcc-plugin-treehydra
%{gccdir}/gcc_treehydra.so

%package doc
Summary:	GCC Dehydra Plugin Documentation
BuildArch:	noarch

%description doc
This package provides HTML documentation for the GCC Dehydra
Plugin, a GCC plugin aimed at tying together JavaScript and GCC
to be able to use JavaScript script from inside the compiler.

%files doc
%doc README

%prep
%setup -q -n %{name}-%{version}

%apply_patches

%build
sed -ri -e 's/\$\(GCC_PLUGIN_HEADERS\)/\$\(GCC_PLUGIN_HEADERS\) \$\(GCC_PLUGIN_HEADERS\)\/c-family/g' Makefile.in
./configure --js-name=mozjs185 --js-lib=%{_libdir} --js-headers=/usr/include/js/
%make

%install
for plugin in gcc_dehydra.so gcc_treehydra.so; do
	%{__install} -m755 -D $plugin %{buildroot}/%{gccdir}/$plugin
done;

%clean
rm -fr %{buildroot}
